version: '1.0'

services:
  db:
    container_name: victal-circle-db
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: victal-circle-api
    build:
      context: .
      dockerfile: Dockerfile.nest
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  pgdata: {}
