version: '1.0.0'

services:
  api:
    build: .
    ports:
      - '3010:3010'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: victal-circle_user
      POSTGRES_PASSWORD: victal-circle_password
      POSTGRES_DB: victal-circle
